### ISSUE TITLE
TypeError when doing tracker.get_stats()

### ISSUE THREAD

**Issue by RetardedGenji** [mattp111/fortniteapi#1]
Hey,
First of all very nice work and thank you very much for posting it's seems great !
But unfortunately I can't use it since i get a TypeError whenever i do `tracker.get_stats()`
i tried to fix it but nothing worked, can you do something ?

Error Message : `the JSON object must be str, not 'bytes'`, line 27 in get_stats `self.parsed = json.loads(resp)`

**Comment by PythonicChemist** [comment]
Can you post your relevant code?  What does print(resp) output if you insert it before line 27? I think the response didn't go well.

**Comment by RetardedGenji** [comment]
it's a discord bot command, quick question, do i need to add `TRN-Api-Key:` in front of the api key or I just take the man part ?

Btw, here is what `print(resp)` shows me (see screenshot, the first line is just my bot that started)
![screenshot](https://user-images.githubusercontent.com/32218033/38098360-29f4ef5c-3378-11e8-8ede-c9c35174ab55.JPG)

**Comment by RetardedGenji** [comment]
Found the issue, here are the changes. Also, don't forget to make a `requirements.txt` since 

> requests

 is a module that needs to be downloaded:
```
import requests
import json
import sys

class tracker:

    def __init__(self, api_key, user=None, platform=None, user_agent=None):
        self.api_key = api_key
        if user_agent != None:
            self.user_agent = user_agent
        else:
            self.user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
        if user != None:
            self.user = user
        if platform != None:
            self.platform = platform

    # Get stats method to get and parse statistics from fortnitetracker api
    def get_stats(self):
        url = "http://api.fortnitetracker.com/v1/profile/" + self.platform + "/" + self.user # Set url based on variables
        header = {"TRN-Api-Key": self.api_key, "User-Agent": self.user_agent} # Configure header with api key and user agent
        r = requests.get(url, headers=header) #Parse the request
        self.parsed = r.json() # JSONify the whole thing ```

**Comment by RetardedGenji** [comment]
I'm too lazy to do one but its just changing 2/3 lines , Sorry
Also, I suggest you to make the same module but using AIOHTTP and not requests since a lot of people are also working with asynchronous things (discord bot for example)

**Comment by mattp111** [comment]
Sorry I didn't respond to this one I havnt had working internet for the past week. I am pushing your solution to the repo.
